### ISSUE TITLE
EISDIR error when converting to Istanbul format

### ISSUE THREAD

**Issue by chriscapaci** [bcoe/c8#12]
I'm seeing this error:

`{ Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at new CovScript (/home/chris/Code/WK/UsageAnalyticsLib/node_modules/v8-to-istanbul/lib/script.js:14:23)
    at module.exports (/home/chris/Code/WK/UsageAnalyticsLib/node_modules/v8-to-istanbul/index.js:4:10)
    at allV8Coverage.forEach (/home/chris/Code/WK/UsageAnalyticsLib/node_modules/c8/bin/c8.js:95:20)
    at Array.forEach (<anonymous>)
    at writeIstanbulFormatCoverage (/home/chris/Code/WK/UsageAnalyticsLib/node_modules/c8/bin/c8.js:94:17)
    at executeWithCoverage (/home/chris/Code/WK/UsageAnalyticsLib/node_modules/c8/bin/c8.js:68:5)
    at <anonymous> errno: -21, code: 'EISDIR', syscall: 'read' }`

I was able to fix it locally in my project by putting an isFile check before creating a CovScript so it doesn't attempt to create coverage files for directories. I then forked this repo and was going to put a fix in, but it looks like 2.0.0 on NPM and the code that is latest here aren't the same. So I'm creating an issue instead. Can someone fix this and release to NPM as a patch? I'd really like to use this tool as I can finally get code coverage with tests using JSDOM.

**Comment by chriscapaci** [comment]
I was able to get around the issue by --include all the files I wanted to instrument. I still think there should be a fix for it though.

**Comment by bcoe** [comment]
@chriscapaci c8 has been overhauled, I'd try things out as they stand right now and see if you're still having issues.
