### ISSUE TITLE
Uncovered branch

### ISSUE THREAD

**Issue by concatime** [bcoe/c8#196]
```sh
node -v
# v13.7.0
```
I use the official binary form NodeJS.org on a 64bit GNU+Linux platform.

Hi. I’m trying to setup a [template repo.](//github.com/concatime/node-sample) using ESM. _Almost_ everything works. When I run the coverage, I get:
```
---------------------|---------|----------|---------|---------|-------------------
File                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
---------------------|---------|----------|---------|---------|-------------------
All files            |     100 |    64.71 |     100 |     100 |                   
 entities.ts         |     100 |       60 |     100 |     100 | 35                
 inversify.config.ts |     100 |      100 |     100 |     100 |                   
 types.ts            |     100 |      100 |     100 |     100 |                   
---------------------|---------|----------|---------|---------|-------------------
```

My issue is that `entities.ts#35` is merely `export { Katana, Ninja, Shuriken };`.
In `inversify.config.ts`, I import everything `import { Katana, Ninja, Shuriken } from './entities';`, so this line should be covered. Am I doing something wrong, or is it a bug in C8?

Thank you.

**Comment by concatime** [comment]
https://github.com/mochajs/mocha/issues/3006#issuecomment-581638261

**Comment by bcoe** [comment]
@concatime when I try to run your example repo I get this error:

```bash
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_INVALID_RETURN_PROPERTY_VALUE]: Expected string to be returned for the "format" from the "loader getFormat" function but got type object.
    at Loader.getFormat (internal/modules/esm/loader.js:110:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Loader.getModuleJob (internal/modules/esm/loader.js:192:20)
    at async Loader.import (internal/modules/esm/loader.js:166:17) {
  code: 'ERR_INVALID_RETURN_PROPERTY_VALUE'
}
npm ERR! Test failed.  See above for more details.
```

Do you have a minimal reproduction I could use to try to hunt down the issue?

**Comment by concatime** [comment]
I have no issue running my template. Have you followed the readme file? Which node version do you have?

**Comment by concatime** [comment]
I updated the repo, it should be solved now.
