### ISSUE TITLE
Unit tests failing for clean clone of master

### ISSUE THREAD

**Issue by j03m** [bcoe/c8#216]
* **Version**: Hash : 56b77232ddc701f3334a86a5bd88bb4bbbb2d0e0
* **Platform**: osx

Seems like something went off the rails with a previous merge. 

**Edit to add: Seems like pulling in the new reporter broke the snapshots. Previous examples that were in the format of `\d+,\d+` have turned into `\d-\d`. If we're okay with that I will submit a PR to update the snapshots and fix whatever is up with the cobertura test

Running `npm test` results in: 

```

> c8@7.1.1 test /Users/jmordetsky/c8
> node ./bin/c8.js mocha --timeout=8000 ./test/*.js



  c8
    ✓ reports coverage for script that exits normally (805ms)
    ✓ supports exeternally set NODE_V8_COVERAGE (822ms)
    ✓ merges reports from subprocesses together (429ms)
    ✓ allows relative files to be included (477ms)
    ✓ exits with 1 when report output fails (520ms)
    1) cobertura report escapes special characters
    check-coverage
      ✓ exits with 0 if coverage within threshold (182ms)
      ✓ exits with 1 if coverage is below threshold (185ms)
      ✓ allows threshold to be applied on per-file basis (184ms)
      ✓ allows --check-coverage when executing script (803ms)
    report
      ✓ generates report from existing temporary files (224ms)
      ✓ supports --check-coverage, when generating reports (231ms)
    ESM Modules
      2) collects coverage for ESM modules
    /* c8 ignore next */
      3) ignores lines with special comment
    source-maps
      TypeScript
        4) remaps branches
        5) remaps classes
      UglifyJS
        6) remaps branches
        7) remaps classes
      nyc
        ✓ remaps branches (293ms)
        8) remaps classes
    ts-node
      9) reads source-map from cache, and applies to coverage
    --all
      10) reports coverage for unloaded js files as 0 for line, branch and function
      11) reports coverage for unloaded transpiled ts files as 0 for line, branch and function
      12) reports coverage for unloaded ts files as 0 for line, branch and function when using ts-node
      13) should allow for --all to be used in conjunction with --check-coverage
      ✓ should allow for --all to be used with the check-coverage command (2 invocations) (832ms)

  c8 on Node.js < 10
    ✓ skip coverage (169ms)

  parse-args
    hideInstrumenteeArgs
      ✓ hides arguments passed to instrumented app
    hideInstrumenterArgs
      ✓ hides arguments passed to c8 bin
    with NODE_V8_COVERAGE already set
      ✓ should not override it


  17 passing (15s)
  13 failing

  1) c8
       cobertura report escapes special characters:

      AssertionError: expected value to match snapshot c8 cobertura report escapes special characters 1
      + expected - actual

                 <lines>
                   <line number="6" hits="1"/>
                 </lines>
               </method>
      -        <method name="map.<computed>.f" hits="1" signature="()V">
      +        <method name="map.&lt;computed&gt;.f" hits="1" signature="()V">
                 <lines>
                   <line number="8" hits="1"/>
                 </lines>
               </method>
      
      at Context.<anonymous> (test/integration.js:450:39)
      at processImmediate (internal/timers.js:439:21)

  2) c8
       ESM Modules
         collects coverage for ESM modules:

      AssertionError: expected value to match snapshot c8 ESM Modules collects coverage for ESM modules 1
      + expected - actual

       File        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
       ------------|---------|----------|---------|---------|-------------------
       All files   |   83.33 |      100 |   66.67 |   83.33 |                   
        export.cjs |     100 |      100 |     100 |     100 |                   
      - export.mjs |   71.43 |      100 |      50 |   71.43 | 2,3               
      + export.mjs |   71.43 |      100 |      50 |   71.43 | 2-3               
        import.mjs |     100 |      100 |     100 |     100 |                   
       ------------|---------|----------|---------|---------|-------------------
       ,"
      
      at Context.<anonymous> (test/integration.js:217:38)
      at processImmediate (internal/timers.js:439:21)

  3) c8
       /* c8 ignore next */
         ignores lines with special comment:

      AssertionError: expected value to match snapshot c8 /* c8 ignore next */ ignores lines with special comment 1
      + expected - actual

       File               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
       -------------------|---------|----------|---------|---------|-------------------
       All files          |   86.21 |    91.67 |   66.67 |   86.21 |                   
        async.js          |     100 |      100 |     100 |     100 |                   
      - c8-ignore-next.js |   90.91 |      100 |     100 |   90.91 | 21,22             
      + c8-ignore-next.js |   90.91 |      100 |     100 |   90.91 | 21-22             
        normal.js         |      75 |    66.67 |   33.33 |      75 | 14-16,18-20       
       -------------------|---------|----------|---------|---------|-------------------
       ,"
      
      at Context.<anonymous> (test/integration.js:231:38)
      at processImmediate (internal/timers.js:439:21)

  4) c8
       source-maps
         TypeScript
           remaps branches:

      AssertionError: expected value to match snapshot c8 source-maps TypeScript remaps branches 1
      + expected - actual

       ------------------------|---------|----------|---------|---------|-------------------
       File                    | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
       ------------------------|---------|----------|---------|---------|-------------------
       All files               |      84 |    57.14 |     100 |      84 |                   
      - branches.typescript.ts |      84 |    57.14 |     100 |      84 | 7,11,12,18        
      + branches.typescript.ts |      84 |    57.14 |     100 |      84 | 7,11-12,18        
       ------------------------|---------|----------|---------|---------|-------------------
       ,"
      
      at Context.<anonymous> (test/integration.js:250:40)
      at processImmediate (internal/timers.js:439:21)

  5) c8
       source-maps
         TypeScript
           remaps classes:

      AssertionError: expected value to match snapshot c8 source-maps TypeScript remaps classes 1
      + expected - actual

       -----------------------|---------|----------|---------|---------|-------------------
       File                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
       -----------------------|---------|----------|---------|---------|-------------------
       All files              |   81.82 |     87.5 |      60 |   81.82 |                   
      - classes.typescript.ts |   81.82 |     87.5 |      60 |   81.82 | 12,13,21,22,27,28 
      + classes.typescript.ts |   81.82 |     87.5 |      60 |   81.82 | 12-13,21-22,27-28 
       -----------------------|---------|----------|---------|---------|-------------------
       ,"
      
      at Context.<anonymous> (test/integration.js:264:40)
      at processImmediate (internal/timers.js:439:21)

  6) c8
       source-maps
         UglifyJS
           remaps branches:

      AssertionError: expected value to match snapshot c8 source-maps UglifyJS remaps branches 1
      + expected - actual

       -------------|---------|----------|---------|---------|-------------------
       File         | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
       -------------|---------|----------|---------|---------|-------------------
       All files    |      80 |       50 |     100 |      80 |                   
      - branches.js |      80 |       50 |     100 |      80 | 2,5,6,13          
      + branches.js |      80 |       50 |     100 |      80 | 2,5-6,13          
       -------------|---------|----------|---------|---------|-------------------
       ,"
      
      at Context.<anonymous> (test/integration.js:280:40)
      at processImmediate (internal/timers.js:439:21)

  7) c8
       source-maps
         UglifyJS
           remaps classes:

      AssertionError: expected value to match snapshot c8 source-maps UglifyJS remaps classes 1
      + expected - actual

       ------------|---------|----------|---------|---------|-------------------
       File        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
       ------------|---------|----------|---------|---------|-------------------
       All files   |   85.19 |    83.33 |      60 |   85.19 |                   
      - classes.js |   85.19 |    83.33 |      60 |   85.19 | 6,7,15,21         
      + classes.js |   85.19 |    83.33 |      60 |   85.19 | 6-7,15,21         
       ------------|---------|----------|---------|---------|-------------------
       ,"
      
      at Context.<anonymous> (test/integration.js:294:40)
      at processImmediate (internal/timers.js:439:21)

  8) c8
       source-maps
         nyc
           remaps classes:

      AssertionError: expected value to match snapshot c8 source-maps nyc remaps classes 1
      + expected - actual

       ------------|---------|----------|---------|---------|-------------------
       File        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
       ------------|---------|----------|---------|---------|-------------------
       All files   |   70.37 |    66.67 |      60 |   70.37 |                   
      - classes.js |   70.37 |    66.67 |      60 |   70.37 | 5-8,15,16,21,22   
      + classes.js |   70.37 |    66.67 |      60 |   70.37 | 5-8,15-16,21-22   
       ------------|---------|----------|---------|---------|-------------------
       ,"
      
      at Context.<anonymous> (test/integration.js:326:40)
      at processImmediate (internal/timers.js:439:21)

  9) c8
       ts-node
         reads source-map from cache, and applies to coverage:

      AssertionError: expected value to match snapshot c8 ts-node reads source-map from cache, and applies to coverage 1
      + expected - actual

       ------------------|---------|----------|---------|---------|-------------------
       File              | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
       ------------------|---------|----------|---------|---------|-------------------
       All files         |   88.24 |     87.5 |      80 |   88.24 |                   
      - ts-node-basic.ts |   88.24 |     87.5 |      80 |   88.24 | 12,13,28,29       
      + ts-node-basic.ts |   88.24 |     87.5 |      80 |   88.24 | 12-13,28-29       
       ------------------|---------|----------|---------|---------|-------------------
       ,"
      
      at Context.<anonymous> (test/integration.js:343:38)
      at next (node_modules/rimraf/rimraf.js:69:7)
      at CB (node_modules/rimraf/rimraf.js:100:9)
      at FSReqCallback.oncomplete (fs.js:146:23)

  10) c8
       --all
         reports coverage for unloaded js files as 0 for line, branch and function:

      AssertionError: expected value to match snapshot c8 --all reports coverage for unloaded js files as 0 for line, branch and function 1
      + expected - actual

       File          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
       --------------|---------|----------|---------|---------|-------------------
       All files     |   64.29 |    66.67 |      50 |   64.29 |                   
        vanilla      |   78.26 |       75 |     100 |   78.26 |                   
      -  loaded.js   |   73.68 |    71.43 |     100 |   73.68 | 4,5,16-18         
      +  loaded.js   |   73.68 |    71.43 |     100 |   73.68 | 4-5,16-18         
         main.js     |     100 |      100 |     100 |     100 |                   
        vanilla/dir  |       0 |        0 |       0 |       0 |                   
         unloaded.js |       0 |        0 |       0 |       0 | 1-5               
       --------------|---------|----------|---------|---------|-------------------
      
      at Context.<anonymous> (test/integration.js:358:38)
      at processImmediate (internal/timers.js:439:21)

  11) c8
       --all
         reports coverage for unloaded transpiled ts files as 0 for line, branch and function:

      AssertionError: expected value to match snapshot c8 --all reports coverage for unloaded transpiled ts files as 0 for line, branch and function 1
      + expected - actual

       File             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
       -----------------|---------|----------|---------|---------|-------------------
       All files        |   64.29 |    66.67 |      50 |   64.29 |                   
        ts-compiled     |   78.26 |       75 |     100 |   78.26 |                   
      -  loaded.ts      |   73.68 |    71.43 |     100 |   73.68 | 4,5,16-18         
      +  loaded.ts      |   73.68 |    71.43 |     100 |   73.68 | 4-5,16-18         
         main.ts        |     100 |      100 |     100 |     100 |                   
        ts-compiled/dir |       0 |        0 |       0 |       0 |                   
         unloaded.ts    |       0 |        0 |       0 |       0 | 1-5               
       -----------------|---------|----------|---------|---------|-------------------
      
      at Context.<anonymous> (test/integration.js:372:38)
      at processImmediate (internal/timers.js:439:21)

  12) c8
       --all
         reports coverage for unloaded ts files as 0 for line, branch and function when using ts-node:

      AssertionError: expected value to match snapshot c8 --all reports coverage for unloaded ts files as 0 for line, branch and function when using ts-node 1
      + expected - actual

       File          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
       --------------|---------|----------|---------|---------|-------------------
       All files     |   64.29 |    66.67 |      50 |   64.29 |                   
        ts-only      |   78.26 |       75 |     100 |   78.26 |                   
      -  loaded.ts   |   73.68 |    71.43 |     100 |   73.68 | 4,5,16-18         
      +  loaded.ts   |   73.68 |    71.43 |     100 |   73.68 | 4-5,16-18         
         main.ts     |     100 |      100 |     100 |     100 |                   
        ts-only/dir  |       0 |        0 |       0 |       0 |                   
         unloaded.ts |       0 |        0 |       0 |       0 | 1-5               
       --------------|---------|----------|---------|---------|-------------------
      
      at Context.<anonymous> (test/integration.js:386:38)
      at processImmediate (internal/timers.js:439:21)

  13) c8
       --all
         should allow for --all to be used in conjunction with --check-coverage:

      AssertionError: expected value to match snapshot c8 --all should allow for --all to be used in conjunction with --check-coverage 1
      + expected - actual

       File          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
       --------------|---------|----------|---------|---------|-------------------
       All files     |   64.29 |    66.67 |      50 |   64.29 |                   
        vanilla      |   78.26 |       75 |     100 |   78.26 |                   
      -  loaded.js   |   73.68 |    71.43 |     100 |   73.68 | 4,5,16-18         
      +  loaded.js   |   73.68 |    71.43 |     100 |   73.68 | 4-5,16-18         
         main.js     |     100 |      100 |     100 |     100 |                   
        vanilla/dir  |       0 |        0 |       0 |       0 |                   
         unloaded.js |       0 |        0 |       0 |       0 | 1-5               
       --------------|---------|----------|---------|---------|-------------------
      
      at Context.<anonymous> (test/integration.js:402:38)
      at processImmediate (internal/timers.js:439:21)



--------------------------|---------|----------|---------|---------|--------------------------------
File                      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s              
--------------------------|---------|----------|---------|---------|--------------------------------
All files                 |   96.05 |    82.83 |     100 |   96.05 |                                
 bin                      |   96.15 |      100 |     100 |   96.15 |                                
  c8.js                   |   96.15 |      100 |     100 |   96.15 | 51,52                          
 lib                      |   95.25 |    76.47 |     100 |   95.25 |                                
  is-cjs-esm-bridge.js    |      90 |     62.5 |     100 |      90 | 9                              
  parse-args.js           |    97.2 |    58.33 |     100 |    97.2 | 97,98,120,121                  
  report.js               |   94.32 |    84.09 |     100 |   94.32 | ...4-87,98-102,220,221,249-251 
  source-map-from-file.js |      96 |       75 |     100 |      96 | 17                             
 lib/commands             |     100 |       95 |     100 |     100 |                                
  check-coverage.js       |     100 |    92.31 |     100 |     100 | 17                             
  report.js               |     100 |      100 |     100 |     100 |                                
--------------------------|---------|----------|---------|---------|--------------------------------

**Comment by j03m** [comment]
CC: @bcoe

**Comment by j03m** [comment]
Closing. I didn't re-install. :/
