### ISSUE TITLE
Array of `--reporter` fails

### ISSUE THREAD

**Issue by Sparticuz** [bcoe/c8#334]
* **Version**: 7.10.0
* **Platform**: Node 14.18.1

Running c8 fails when an array of reporters is added

```
$ npx c8 --reporter=['lcov','text'] ava
...
Error: Cannot find module '[lcov,text]'
Require stack:
- /home/kyle/dev/task-runner/node_modules/istanbul-reports/index.js
- /home/kyle/dev/task-runner/node_modules/c8/lib/report.js
- /home/kyle/dev/task-runner/node_modules/c8/lib/commands/check-coverage.js
- /home/kyle/dev/task-runner/node_modules/c8/lib/commands/report.js
- /home/kyle/dev/task-runner/node_modules/c8/bin/c8.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.create (/home/kyle/dev/task-runner/node_modules/istanbul-reports/index.js:19:20)
    at Report.run (/home/kyle/dev/task-runner/node_modules/c8/lib/report.js:71:15)
    at async exports.outputReport (/home/kyle/dev/task-runner/node_modules/c8/lib/commands/report.js:38:3)
    at async /home/kyle/dev/task-runner/node_modules/c8/bin/c8.js:39:9
```

**Comment by jcubic** [comment]
I think that the syntax is:
```
npx c8 --reporter=lcov --reporter=text ava
```
if library is compatible with istanbul: https://istanbul.js.org/docs/tutorials/ava/

**Comment by evisong** [comment]
> I think that the syntax is:
> 
> ```
> npx c8 --reporter=lcov --reporter=text ava
> ```
> 
> if library is compatible with istanbul: https://istanbul.js.org/docs/tutorials/ava/
> 
> The array is probably just what command line parser returns.

Your hints save my day, many thanks! 

I've recently upgraded my CI docker image to `16.16.0-alpine3.15`, then

```json
    "coverage": "c8 --all --include=src --reporter={lcov,text} mocha",
```

fails with message: `Error: Cannot find module '{lcov,text}'`.

Changing into:

```json
    "coverage": "c8 --all --include=src --reporter=lcov --reporter=text mocha",
```

fixes this.
