### ISSUE TITLE
Bug in @bcoe/v8-coverage: undefined is not iterable

### ISSUE THREAD

**Issue by sebbo2002** [bcoe/c8#542]
* **Version**: v18.20.4 and v20.12.2
* **Platform**: Darwin 23.6.0 Kernel Version 23.6.0 / GitHub Runner Ubuntu 22.0.4 LTS

There seems to be a bug in `@bcoe/v8-coverage` that I am currently struggling with in [this repository](https://github.com/sebbo2002/vestaboard2mqtt).
I get the following error at the [end of the test](https://github.com/sebbo2002/vestaboard2mqtt/actions/runs/10514916473/job/29133869864?pr=209#step:6:132):

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at RangeTree.fromSortedRanges (/home/runner/work/vestaboard2mqtt/vestaboard2mqtt/node_modules/@bcoe/v8-coverage/dist/lib/range-tree.js:27:39)
    at normalizeFunctionCov (/home/runner/work/vestaboard2mqtt/vestaboard2mqtt/node_modules/@bcoe/v8-coverage/dist/lib/normalize.js:74:41)
    at Object.deepNormalizeScriptCov (/home/runner/work/vestaboard2mqtt/vestaboard2mqtt/node_modules/@bcoe/v8-coverage/dist/lib/normalize.js:59:9)
    at mergeScriptCovs (/home/runner/work/vestaboard2mqtt/vestaboard2mqtt/node_modules/@bcoe/v8-coverage/dist/lib/merge.js:59:21)
    at mergeProcessCovs (/home/runner/work/vestaboard2mqtt/vestaboard2mqtt/node_modules/@bcoe/v8-coverage/dist/lib/merge.js:34:21)
    at Report._getMergedProcessCov (/home/runner/work/vestaboard2mqtt/vestaboard2mqtt/node_modules/c8/lib/report.js:336:12)
    at Report.getCoverageMapFromAllCoverageFiles (/home/runner/work/vestaboard2mqtt/vestaboard2mqtt/node_modules/c8/lib/report.js:245:27)
    at Report.run (/home/runner/work/vestaboard2mqtt/vestaboard2mqtt/node_modules/c8/lib/report.js:84:31)
    at exports.outputReport (/home/runner/work/vestaboard2mqtt/vestaboard2mqtt/node_modules/c8/lib/commands/report.js:42:16)
    at /home/runner/work/vestaboard2mqtt/vestaboard2mqtt/node_modules/c8/bin/c8.js:30:15
```

There is already [a pull request for this](https://github.com/demurgos/v8-coverage/pull/80) in the forked repository. This pull request solves the problem for me. Would it be possible to merge this patch into `@bcoe/v8-coverage` and use this new version to fix the bug? Thank you very much.

**Comment by cenfun** [comment]
Try `c8 --experimental-monocart mocha` to see if the error still exists

**Comment by cenfun** [comment]
BTW, the PR is [here](https://github.com/bcoe/v8-coverage/pull/2)

**Comment by sebbo2002** [comment]
@cenfun Ah thanks, I hadn't found that one. Then I can close this ticket here, right?

**Comment by cenfun** [comment]
Yes, it should be fixed in [v8-coverage](https://github.com/bcoe/v8-coverage) not [c8](https://github.com/bcoe/c8)
